apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: smartlight
type: Opaque
stringData:
  POSTGRES_DB: light
  POSTGRES_USER: light
  POSTGRES_PASSWORD: Secret1
  DB_URL: jdbc:postgresql://postgres-service:5432/light
  DB_USER: light
  DB_PASSWORD: Secret1
